#!/usr/bin/env sh
#
# DESCRIPTION:
#   This a simple script that loads an ASCII art in the origin path of this.
#
#   It will look for art that can be loaded in the terminal size.
#   So I do recommend you to have multiple arts.
#
#   If you want nincat to print faster, then just use a POSIX-compliant shell,
#   I do recommend dash (which as 4x faster than bash).
#
# MAINTAINER:
#   BeyondMagic : 2021- : koetemagie@gmail.com
#
# GPL3 © 2021 : github.com/BeyondMagic/nincat

path_script="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"

columns=$(tput cols)

# Select art
selected="$(find \
  "$path_script/ascii_arts/" \
  -type f -size +0 | \
   awk "(\$(NF-1) <= $(($(tput lines) - 1))) && (\$NF <= $columns)" | \
   shuf | head -n1)"

# Did not find?
[ "$selected" ] && {

  # Print name
  #printf "$selected\n" | sed "s*$path_script/ascii_arts/**" | \
  #  awk '{print $(NF-2), $(NF-1), $NF}'

  # Get our art from path
  art="$(sed "s/^/$(printf %$((\
    (columns - $(printf "$selected" | grep -oE '[^ ]+$'))\
    / 2 ))s)/" "$selected")"

  # If there isn't lolcat, then it will use the first printf
  [ $(printf "$selected" | grep -c 'lolcat') = 0 ] && \
    printf "$art\n\033[0m" || \
    printf "$art\n" | lolcat -r

}
